# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(293, 180)
        self.mainLayout = QtWidgets.QVBoxLayout(Form)
        self.mainLayout.setObjectName("mainLayout")
        self.group_1 = QtWidgets.QHBoxLayout()
        self.group_1.setObjectName("group_1")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setObjectName("label_1")
        self.group_1.addWidget(self.label_1)
        self.spinBox_1 = QtWidgets.QLineEdit(Form)
        self.spinBox_1.setObjectName("spinBox_1")
        self.group_1.addWidget(self.spinBox_1)
        self.mainLayout.addLayout(self.group_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QLineEdit(Form)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.mainLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.mainLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.info_show_hide_button = QtWidgets.QPushButton(Form)
        self.info_show_hide_button.setObjectName("info_show_hide_button")
        self.horizontalLayout_4.addWidget(self.info_show_hide_button)
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_4.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.algorithm_info = QtWidgets.QLabel(Form)
        self.algorithm_info.setObjectName("algorithm_info")
        self.verticalLayout.addWidget(self.algorithm_info)
        self.mainLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "Capital"))
        self.label_2.setText(_translate("Form", "Window"))
        self.radioButton_3.setText(_translate("Form", "low risk"))
        self.radioButton_2.setText(_translate("Form", "medium risk"))
        self.radioButton.setText(_translate("Form", "high risk"))
        self.info_show_hide_button.setText(_translate("Form", "SHOW INFO"))
        self.close_button.setText(_translate("Form", "CLOSE"))
        self.algorithm_info.setText(_translate("Form", "some text about algorithm"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
