# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tradeBot_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 640)
        MainWindow.setMinimumSize(QtCore.QSize(600, 640))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: #2e2f33;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(20, 540, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.run_button.setFont(font)
        self.run_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(\n"
"spread:pad, x1: 0, y1: 0, x2: 1, y2: 0, \n"
"stop: 0  #e38676, stop:1 #d65c66);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"spread:pad, x1: 0, y1: 0, x2: 1, y2: 0, \n"
"stop: 0  #e39486, stop:1 #d66b74);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"spread:pad, x1: 0, y1: 0, x2: 1, y2: 0, \n"
"stop: 0  #e37966, stop:1 #d64d59);\n"
"    }")
        self.run_button.setAutoDefault(False)
        self.run_button.setFlat(False)
        self.run_button.setObjectName("run_button")
        self.ticker_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.ticker_edit.setGeometry(QtCore.QRect(20, 20, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ticker_edit.setFont(font)
        self.ticker_edit.setStyleSheet("background-color: qlineargradient(spread:pad, x1: 0, y1: 0, x2: 1, y2: 0, stop: 0  #5B86E5, stop:1 #36D1DC);\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.ticker_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhPreferUppercase)
        self.ticker_edit.setFrame(False)
        self.ticker_edit.setObjectName("ticker_edit")
        self.dateEdit_from = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_from.setGeometry(QtCore.QRect(20, 120, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.dateEdit_from.setFont(font)
        self.dateEdit_from.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dateEdit_from.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dateEdit_from.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit_from.setStyleSheet("background-color: rgba( 255, 255, 255,90%);\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.dateEdit_from.setFrame(False)
        self.dateEdit_from.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_from.setMaximumDate(QtCore.QDate(3000, 12, 31))
        self.dateEdit_from.setMinimumDate(QtCore.QDate(2000, 9, 14))
        self.dateEdit_from.setObjectName("dateEdit_from")
        self.dateEdit_to = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_to.setGeometry(QtCore.QRect(20, 220, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        self.dateEdit_to.setFont(font)
        self.dateEdit_to.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dateEdit_to.setStyleSheet("background-color: rgba( 255, 255, 255,90%);\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.dateEdit_to.setFrame(False)
        self.dateEdit_to.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_to.setMaximumDate(QtCore.QDate(3000, 12, 31))
        self.dateEdit_to.setMinimumDate(QtCore.QDate(2000, 9, 14))
        self.dateEdit_to.setObjectName("dateEdit_to")
        self.comboBox_alg = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_alg.setGeometry(QtCore.QRect(20, 320, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_alg.setFont(font)
        self.comboBox_alg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_alg.setStyleSheet("QComboBox {\n"
"    border-radius: 10px;\n"
"    background-color: rgba( 255, 255, 255,90%);\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    width: 40px;\n"
"    height: 80px;\n"
"    background-color: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_alg.setCurrentText("ALGORITHM")
        self.comboBox_alg.setFrame(False)
        self.comboBox_alg.setObjectName("comboBox_alg")
        self.comboBox_alg.addItem("")
        self.comboBox_time = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_time.setGeometry(QtCore.QRect(20, 420, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_time.setFont(font)
        self.comboBox_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_time.setStyleSheet("QComboBox {\n"
"    border-radius: 10px;\n"
"    background-color: rgba( 255, 255, 255,90%);\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    width: 40px;\n"
"    height: 80px;\n"
"    background-color: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_time.setCurrentText("TIME FRAME")
        self.comboBox_time.setFrame(False)
        self.comboBox_time.setObjectName("comboBox_time")
        self.comboBox_time.addItem("")
        self.status_field = QtWidgets.QTextBrowser(self.centralwidget)
        self.status_field.setGeometry(QtCore.QRect(310, 540, 650, 80))
        self.status_field.setMinimumSize(QtCore.QSize(250, 80))
        self.status_field.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.status_field.setFont(font)
        self.status_field.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid white;\n"
"border-radius: 5px;\n"
"padding: 10px;")
        self.status_field.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.status_field.setObjectName("status_field")
        self.graphic_field = QtWidgets.QWidget(self.centralwidget)
        self.graphic_field.setGeometry(QtCore.QRect(310, 20, 650, 480))
        self.graphic_field.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.graphic_field.setFont(font)
        self.graphic_field.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphic_field.setStyleSheet("background-color: #2e2f33;\n"
"border: 1px solid white;\n"
"border-radius: 5px;")
        self.graphic_field.setObjectName("graphic_field")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trade Bot"))
        self.run_button.setText(_translate("MainWindow", "RUN"))
        self.comboBox_alg.setItemText(0, _translate("MainWindow", "ALGORITHM"))
        self.comboBox_time.setItemText(0, _translate("MainWindow", "TIME FRAME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
